import { randomUUID } from 'crypto';
import { extname, join, resolve, sep } from 'path';

/**
 * Shared upload safety helpers.
 *
 * Two rules every upload path must follow:
 *  1. The on-disk name is generated by the server, never derived from
 *     `file.name`. A user-supplied name is data, not a path.
 *  2. The resolved destination is asserted to sit inside the intended
 *     directory before anything is written.
 */

/** Default 10MB, matching MAX_FILE_SIZE in .env.example and fileUploadSchema. */
export const DEFAULT_MAX_UPLOAD_BYTES = 10 * 1024 * 1024;

export function maxUploadBytes(): number {
  const configured = Number(process.env.MAX_FILE_SIZE);
  return Number.isFinite(configured) && configured > 0
    ? configured
    : DEFAULT_MAX_UPLOAD_BYTES;
}

export class UploadError extends Error {
  constructor(
    message: string,
    readonly status: number
  ) {
    super(message);
    this.name = 'UploadError';
  }
}

/**
 * Lowercased extension including the leading dot, e.g. ".pdf".
 * Returns '' when the name carries no extension.
 */
export function fileExtension(originalName: string): string {
  return extname(originalName).toLowerCase();
}

/**
 * Rejects before the body is buffered into memory. `file.size` is set by
 * the runtime from the multipart part, so this does not require reading
 * the file first.
 */
export function assertWithinSizeLimit(file: File): void {
  const limit = maxUploadBytes();
  if (file.size > limit) {
    throw new UploadError(
      `File exceeds the ${Math.floor(limit / (1024 * 1024))}MB upload limit`,
      413
    );
  }
}

export function assertAllowedExtension(
  originalName: string,
  allowed: readonly string[]
): string {
  const ext = fileExtension(originalName);
  if (!allowed.includes(ext)) {
    throw new UploadError(
      `Unsupported file type. Allowed: ${allowed.join(', ')}`,
      400
    );
  }
  return ext;
}

/**
 * Builds a destination path with a server-generated basename, then asserts
 * containment. The containment check is belt-and-braces given the random
 * name, but it is what makes the guarantee independent of that choice.
 */
export function safeUploadPath(uploadsDir: string, ext: string): string {
  const filePath = join(uploadsDir, `${randomUUID()}${ext}`);
  const root = resolve(uploadsDir);
  if (!resolve(filePath).startsWith(root + sep)) {
    throw new UploadError('Resolved upload path escapes the upload directory', 400);
  }
  return filePath;
}

/** Maps an UploadError to its status; anything else is a 500. */
export function uploadErrorStatus(error: unknown): number {
  return error instanceof UploadError ? error.status : 500;
}
