import { randomUUID } from 'crypto';
import { extname, join, resolve, sep } from 'path';
import { countWords } from './utils/documentProcessor';

/**
 * Shared upload safety helpers.
 *
 * Two rules every upload path must follow:
 *  1. The on-disk name is generated by the server, never derived from
 *     `file.name`. A user-supplied name is data, not a path.
 *  2. The resolved destination is asserted to sit inside the intended
 *     directory before anything is written.
 */

/** Default 10MB, matching MAX_FILE_SIZE in .env.example and fileUploadSchema. */
export const DEFAULT_MAX_UPLOAD_BYTES = 10 * 1024 * 1024;

export function maxUploadBytes(): number {
  const configured = Number(process.env.MAX_FILE_SIZE);
  return Number.isFinite(configured) && configured > 0
    ? configured
    : DEFAULT_MAX_UPLOAD_BYTES;
}

export class UploadError extends Error {
  constructor(
    message: string,
    readonly status: number
  ) {
    super(message);
    this.name = 'UploadError';
  }
}

/**
 * Lowercased extension including the leading dot, e.g. ".pdf".
 * Returns '' when the name carries no extension.
 */
export function fileExtension(originalName: string): string {
  return extname(originalName).toLowerCase();
}

/**
 * The exact per-file limit, checked once the part is in hand.
 *
 * This does NOT bound memory on its own: `file.size` is only known after the
 * multipart body has been parsed, and parsing buffers it. Reaching this
 * function at all means the bytes were already read. `readCappedFormData` is
 * what stops an oversized body before that happens; this is what enforces the
 * limit precisely afterwards. (SEC-10)
 */
export function assertWithinSizeLimit(file: File): void {
  const limit = maxUploadBytes();
  if (file.size > limit) {
    throw new UploadError(
      `File exceeds the ${Math.floor(limit / (1024 * 1024))}MB upload limit`,
      413
    );
  }
}

/**
 * The multipart envelope around the file: boundary lines, per-part headers,
 * and the handful of small text fields that travel with it (`incidentId`, or
 * a policy's title and facets). Generous on purpose -- the ceiling here only
 * has to bound memory, and `assertWithinSizeLimit` enforces the real limit on
 * the file itself once it has been parsed.
 */
const MULTIPART_OVERHEAD_BYTES = 64 * 1024;

/** What `readCappedFormData` needs of a Request. Both routes pass a NextRequest. */
interface MultipartRequest {
  headers: Headers;
  body: ReadableStream<Uint8Array> | null;
}

/**
 * Reads a multipart body under a hard byte ceiling.
 *
 * Both upload routes called `request.formData()` and then checked `file.size`,
 * with a comment claiming the check ran "before buffering the body". It did
 * not: `formData()` reads the whole request into memory first, so the size
 * limit rejected an oversized file only after paying for it. A few concurrent
 * multi-hundred-megabyte POSTs from one signed-in account were enough to take
 * the process down, which on a single-replica deployment is every
 * administrator. (SEC-10)
 *
 * Content-Length is checked first because it is free and rejects the honest
 * case without reading a byte. It is not sufficient on its own -- it is absent
 * under chunked transfer encoding and it can simply lie -- so the body is also
 * piped through a counter that errors the moment the ceiling is passed. The
 * bound then holds regardless of what the header claimed, and the parser never
 * sees more than the ceiling.
 */
export async function readCappedFormData(request: MultipartRequest): Promise<FormData> {
  const limit = maxUploadBytes();
  const ceiling = limit + MULTIPART_OVERHEAD_BYTES;
  const tooLarge = () =>
    new UploadError(
      `Upload exceeds the ${Math.floor(limit / (1024 * 1024))}MB limit`,
      413
    );

  const declared = Number(request.headers.get('content-length'));
  if (Number.isFinite(declared) && declared > ceiling) throw tooLarge();

  const body = request.body;
  if (!body) throw new UploadError('Expected a multipart upload body', 400);

  let seen = 0;
  let exceeded = false;
  const counter = new TransformStream<Uint8Array, Uint8Array>({
    transform(chunk, controller) {
      seen += chunk.byteLength;
      if (seen > ceiling) {
        // Erroring the stream is what makes this a bound rather than a
        // measurement: the parser stops, and we stop reading the socket.
        exceeded = true;
        controller.error(tooLarge());
        return;
      }
      controller.enqueue(chunk);
    },
  });

  try {
    return await new Response(body.pipeThrough(counter), {
      headers: { 'content-type': request.headers.get('content-type') ?? '' },
    }).formData();
  } catch (error) {
    // The parser wraps the stream's error, so the flag is what survives.
    if (exceeded) throw tooLarge();
    if (error instanceof UploadError) throw error;
    throw new UploadError('Could not read the upload', 400);
  }
}

export function assertAllowedExtension(
  originalName: string,
  allowed: readonly string[]
): string {
  const ext = fileExtension(originalName);
  if (!allowed.includes(ext)) {
    throw new UploadError(
      `Unsupported file type. Allowed: ${allowed.join(', ')}`,
      400
    );
  }
  return ext;
}

/**
 * Builds a destination path with a server-generated basename, then asserts
 * containment. The containment check is belt-and-braces given the random
 * name, but it is what makes the guarantee independent of that choice.
 */
export function safeUploadPath(uploadsDir: string, ext: string): string {
  const filePath = join(uploadsDir, `${randomUUID()}${ext}`);
  const root = resolve(uploadsDir);
  if (!resolve(filePath).startsWith(root + sep)) {
    throw new UploadError('Resolved upload path escapes the upload directory', 400);
  }
  return filePath;
}

/** Maps an UploadError to its status; anything else is a 500. */
/**
 * A policy whose text could not be read must not become an active policy.
 *
 * Retrieval works from chunks, and chunks come from this text. A row with none
 * is invisible to search while still counting as a loaded policy to anyone
 * reading the library -- and it takes a scanned PDF, not a malformed one, to
 * get here.
 *
 * Lives here, with the other upload rules, because there are three ingestion
 * routes and a guard on one of them is not a guard.
 */
/**
 * Where uploaded files live, resolved one way.
 *
 * There were four expressions for this across six call sites, and they
 * disagreed. Two were wrong in ways that only show up in deployment:
 *
 *   join(cwd, UPLOADS_DIR, 'attachments')
 *
 * silently prefixes the working directory to an absolute path, so
 * UPLOADS_DIR=/app/uploads resolves to /app/app/uploads/attachments -- outside
 * the mounted volume, on a container platform where anything outside the mount
 * dies with the revision. Upload and download shared the same wrong expression,
 * so the app worked perfectly until the first redeploy, at which point every
 * attachment -- student records -- was gone with no error anywhere.
 *
 * And `join(cwd, 'uploads', 'policies')` ignored UPLOADS_DIR entirely, so a
 * policy written by one route was not where `policies:reindex` looked, and its
 * containment check therefore failed every time and re-copied the file on
 * every run.
 *
 * `resolve` is the fix: it honours an absolute UPLOADS_DIR and resolves a
 * relative one against the working directory. (OQ-2, DEAD-62)
 */
export function uploadsRoot(): string {
  return resolve(process.env.UPLOADS_DIR ?? './uploads');
}

/** Policy source documents. `policies:reindex` re-extracts from these. */
export function policyUploadsDir(): string {
  return resolve(uploadsRoot(), 'policies');
}

/** Attachments. Student records: never under `public/`, never in the image. */
export function attachmentUploadsDir(): string {
  return resolve(uploadsRoot(), 'attachments');
}

export function assertIndexablePolicyText(content: string): void {
  if (countWords(content) === 0) {
    throw new UploadError(
      'No text could be extracted from this document. If it is a scan, run it through OCR first.',
      422
    );
  }
}

export function uploadErrorStatus(error: unknown): number {
  return error instanceof UploadError ? error.status : 500;
}
