services:
  - type: web
    name: generalschat-backend
    env: python
    buildCommand: |
      apt-get update && apt-get install -y python3-pip
      curl -fsSL https://ollama.com/install.sh | sh
      pip3 install -r requirements.txt
    startCommand: |
      ollama serve &
      sleep 10
      ollama pull mistral || echo "Failed to pull model"
      uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: MODEL_NAME
        value: mistral
      - key: OLLAMA_HOST
        value: http://localhost:11434 