services:
  - type: web
    name: generalschat-backend
    env: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    envVars:
      - key: MODEL_NAME
        value: mistral
      - key: OLLAMA_HOST
        value: http://localhost:11434 